
Lmod is automatically replacing "intel/2020.1.217" with "gcc/9.3.0".


The following have been reloaded with a version change:
  1) python/3.9.6 => python/3.11.2

venv activated
call python script next
Traceback (most recent call last):
  File "/home/ulaval.ca/lesee/projects/Project2-synergiqc/PFS/src/ML-NT-PFS-all.py", line 285, in <module>
    final_max_scores_df = pd.concat(max_scores_dfs, ignore_index=True)            
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2022a/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2022a/lib/python3.11/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2022a/lib/python3.11/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
